---
- name: reload mongod
  service: name={{ mongodb_daemon_name }} state=reloaded

- name: restart mongod
  service: name={{ mongodb_daemon_name }} state=restarted

- name: mongodb_settings restart
  service: name=mongodb_settings state=restarted